var nMButt=document.getElementById("noticeMenuButt");
var nMBox=document.getElementById("noticeMenuBox");
nMButt.addEventListener("mouseover",stopINMC);
nMButt.addEventListener("mouseover",iNMO);
nMButt.addEventListener("mouseout",stopINMO);
nMButt.addEventListener("mouseout",iNMC);
nMBox.addEventListener("mouseover",stopINMC);
nMBox.addEventListener("mouseover",iNMO);
nMBox.addEventListener("mouseout",stopINMO);
nMBox.addEventListener("mouseout",iNMC);